server.port: 7000
server.error.include-message: always

app:
  todo-service:
    host: localhost
    port: 7001
  user-service:
    host: localhost
    port: 7002

spring:
  datasource:
    url: jdbc:mysql://localhost/user
    username: root
    password: root

logging:
  level:
    root: INFO
    project: DEBUG

project.main.jwtSecret: projectSecretKeyprojectSecretKeyprojectSecretKeyprojectSecretKey
project.main.jwtExpirationMs: 86400000

---
spring.config.activate.on-profile: docker

server.port: 80

app:
  todo-service:
    host: todo
    port: 80
  user-service:
    host: user
    port: 80

spring.datasource:
  url: jdbc:mysql://mysql/user
  username: user
  password: pwd