server.port: 7000
server.error.include-message: always

app:
  todo-service:
    host: localhost
    port: 7001
  user-service:
    host: localhost
    port: 7002

logging:
  level:
    root: INFO
    project: DEBUG

project.main.jwtSecret: projectSecretKeyprojectSecretKeyprojectSecretKeyprojectSecretKey
project.main.jwtExpirationMs: 86400000

spring:
  cloud:
    stream:
      default-binder: rabbit
      default-contentType: application/json
      bindings:
        todo-out-0:
          destination: todo
          producer:
            required-groups: auditGroup
        user-out-0:
          destination: todo
          producer:
            required-groups: auditGroup

      kafka:
        binder:
          brokers: 127.0.0.1
          port: 2181
      rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest

