server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: todo-db

logging:
  level:
    root: INFO
    project: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG