server.port: 7002
server.error.include-message: always

#Set this to "none" in production environment
spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    url: jdbc:mysql://localhost/user-db
    username: root
    password: root

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    project: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/user-db
  username: user
  password: pwd